# Generated by Django 6.0.2 on 2026-03-01 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_description', models.TextField()),
                ('file_type', models.CharField(max_length=50)),
                ('file_uploader', models.CharField(max_length=255)),
                ('file_uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('file_uploaded_to', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(default='not approved yet', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=20)),
                ('joindate', models.CharField(max_length=50)),
                ('image', models.ImageField(default='profile.jpg', upload_to='profilepics/')),
                ('about', models.TextField(default='N/A')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
